// frontend/react/src/components/MainLayout.jsx
import React, { useEffect, useState } from 'react'
import { Header } from './Header'
import { AddTask } from './AddTask'
import { TaskList } from './TaskList'
import { getAllTasks } from '../api/getAllTasks'

export const MainLayout = () => {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchTasks = async () => {
    try {
      const data = await getAllTasks();
      setTasks(data);
      setLoading(false);
    } catch (error) {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, []);
  return (
    <div className='w-screen h-screen flex flex-col items-center bg-zinc-900'>
        <Header />
        <AddTask onRequestSuccess={fetchTasks} />
        <TaskList tasks={tasks} loading={loading} onRequestSuccess={fetchTasks}/>
    </div>
  )
}

// frontend/svelte/src/components/MainLayout.svelte
<script>
    import { onMount } from 'svelte';
    import Header from './Header.svelte';
    import AddTask from './AddTask.svelte';
    import TaskList from './TaskList.svelte';
    import { getAllTasks } from '../api/getAllTasks.js';
  
    let tasks = [];
    let loading = true;
  
    async function fetchTasks() {
      try {
        const data = await getAllTasks();
        tasks = data;
        loading = false;
      } catch (error) {
        loading = false;
      }
    }
  
    onMount(() => {
      fetchTasks();
    });
  
    function handleRequestSuccess() {
      fetchTasks();
    }
</script>
  
<div class="w-screen h-screen flex flex-col items-center bg-zinc-900">
    <Header />
    <AddTask onRequestSuccess={handleRequestSuccess} />
    <TaskList {tasks} {loading} onRequestSuccess={handleRequestSuccess} />
</div>
