// frontend/svelte/src/components/AddTask.svelte
<script>
    import { addTask } from '../api/addTask';
    import Button from './Button.svelte';
  
    export let onRequestSuccess;
  
    let title = '';
  
    const handleTitleChange = (event) => {
      title = event.target.value;
    };
  
    const handleAddTask = async (title) => {
      if (title.length) {
        await addTask({
          title,
          is_completed: false,
        });
        onRequestSuccess();
        title = '';
      }
    };
</script>
  
<div class="flex w-[30rem] h-16 justify-center items-center mb-16">
    <div class="flex">
        <input 
            type="text" 
            name="addTask" 
            id="addTask" 
            class="bg-zinc-700 rounded-l-md h-10 w-[27rem] focus-visible:outline-none text-zinc-50 px-4" 
            placeholder="Add Task" 
            bind:value={title} 
            on:input={handleTitleChange}
        />
        <Button 
            type="add" 
            onClick={async () => await handleAddTask(title)}
        />
    </div>
</div>

// frontend/angular/src/app/add-task/add-task.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { addTask } from '../../api/addTask';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
    selector: 'app-add-task',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './add-task.component.html',
})
export class AddTaskComponent {
    title: string = '';

    @Output() requestSuccess: EventEmitter<void> = new EventEmitter<void>();

    handleTitleChange(event: Event): void {
        this.title = (event.target as HTMLInputElement).value;
    }

    async handleAddTask(): Promise<void> {
        if (this.title.length > 0) {
            try {
                await addTask({
                    title: this.title,
                    is_completed: false
                });
                this.requestSuccess.emit();
                this.title = '';
            } catch (error) {
                console.error('Error adding task:', error);
            }
        }
    }
}

<div class="flex w-[30rem] h-16 justify-center items-center mb-16">
    <div class="flex">
      <input 
        type="text" 
        name="addTask" 
        id="addTask" 
        class="bg-zinc-700 rounded-l-md h-10 w-[27rem] focus-visible:outline-none text-zinc-50 px-4" 
        placeholder="Add Task" 
        [(ngModel)]="title" 
        (input)="handleTitleChange($event)"
      />
      <button 
        class="w-12 text-zinc-900 bg-zinc-400 h-10 flex justify-center items-center rounded-r-md"
        (click)="handleAddTask()"
      >
        Add
      </button>
    </div>
  </div>
