// frontend/svelte/src/components/MainLayout.svelte
<script>
    import { onMount } from 'svelte';
    import Header from './Header.svelte';
    import AddTask from './AddTask.svelte';
    import TaskList from './TaskList.svelte';
    import { getAllTasks } from '../api/getAllTasks.js';
  
    let tasks = [];
    let loading = true;
  
    async function fetchTasks() {
      try {
        const data = await getAllTasks();
        tasks = data;
        loading = false;
      } catch (error) {
        loading = false;
      }
    }
  
    onMount(() => {
      fetchTasks();
    });
  
    function handleRequestSuccess() {
      fetchTasks();
    }
</script>
  
<div class="w-screen h-screen flex flex-col items-center bg-zinc-900">
    <Header />
    <AddTask onRequestSuccess={handleRequestSuccess} />
    <TaskList {tasks} {loading} onRequestSuccess={handleRequestSuccess} />
</div>

// frontend/angular/src/app/main-layout/main-layout.component.ts
import { Component, OnInit } from '@angular/core';
import { getAllTasks } from '../../api/getAllTasks'; // Import your API function for fetching tasks
import { Task } from '../../types';
import { HeaderComponent } from '../header/header.component';
import { AddTaskComponent } from '../add-task/add-task.component';
import { TaskListComponent } from '../task-list/task-list.component';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-main-layout',
    imports: [HeaderComponent, AddTaskComponent, TaskListComponent, CommonModule],
    standalone: true,
    templateUrl: './main-layout.component.html',
})
export class MainLayoutComponent implements OnInit {
    tasks: Task[] = [];
    loading = true;

    constructor() { }

    ngOnInit(): void {
        this.fetchTasks();
    }

    fetchTasks(): void {
        this.loading = true;
        getAllTasks().then(
            (data: Task[]) => {
                this.tasks = data;
                this.loading = false;
            },
            (error) => {
                console.error('Error fetching tasks:', error);
                this.loading = false;
            }
        );
    }

    handleRequestSuccess(): void {
        this.fetchTasks();
    }
}

<div class="w-screen h-screen flex flex-col items-center bg-zinc-900">
    <app-header></app-header>
    <app-add-task (requestSuccess)="handleRequestSuccess()"></app-add-task>
    <app-task-list [tasks]="tasks" (requestSuccess)="handleRequestSuccess()"></app-task-list>
  </div>
