// frontend/svelte/src/components/TaskList.svelte
<script>
    import Task from './Task.svelte';
  
    export let tasks = [];
    export const loading = false;
    export let onRequestSuccess;
  
</script>
  
<span class="text-2xl text-zinc-50 font-semibold mb-4">Tasks</span>
    <div class={`w-[42rem] flex flex-col gap-5 items-center ${!tasks.length ? 'justify-center' : ''} min-h-72 bg-zinc-800 rounded-md p-6`}>
    {#if tasks.length}
        {#each tasks as task (task._id)}
            <Task {task} onRequestSuccess={onRequestSuccess} />
        {/each}
    {:else}
        <span class="text-zinc-50">Task list is empty. Add one!</span>
    {/if}
</div>

// frontend/angular/src/app/task-list/task-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Task } from '../../types';
import { TaskComponent } from '../task/task.component';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-task-list',
    imports: [TaskComponent, CommonModule],
    standalone: true,
    templateUrl: './task-list.component.html',
})
export class TaskListComponent {
    @Input() tasks: Task[] = [];
    @Output() requestSuccess: EventEmitter<void> = new EventEmitter<void>();

    constructor() { }

    handleRequestSuccess(): void {
        this.requestSuccess.emit();
    }
}

<div class="flex flex-col justify-center items-center w-[42rem]">
    <span class="text-2xl text-zinc-50 font-semibold mb-4">Tasks</span>
    <div class="w-[42rem] flex flex-col gap-5 items-center min-h-72 bg-zinc-800 rounded-md p-6"
         [ngClass]="{'justify-center': !tasks?.length}">
      <ng-container *ngIf="tasks?.length; else emptyList">
        <app-task *ngFor="let task of tasks"
                  [task]="task"
                  (requestSuccess)="handleRequestSuccess()">
        </app-task>
      </ng-container>
      <ng-template #emptyList>
        <span class="text-zinc-50">Task list is empty. Add one!</span>
      </ng-template>
    </div>
  </div>
