// frontend/react/src/components/Task.jsx
import React, { useState } from 'react'
import { Button } from './Button'
import { deleteTask } from '../api/deleteTask'
import { editTask } from '../api/editTask';

export const Task = ({ task, onRequestSuccess }) => {
  const [title, setTitle] = useState(task.title);
  const [enableEdit, setEnableEdit] = useState(false);

  const handleTitleChange = (event) => {
    setTitle(event.target.value);
  };

  const handleEditTask = async (id, {title , is_completed}) => {
    const data = {
      title: title ?? task.title,
      is_completed: is_completed ?? task.is_completed,
    }
    await editTask(id, data);
    onRequestSuccess();
    setEnableEdit(false);
  }

  const handleDeleteTask = async (id) => {
    await deleteTask(id);
    onRequestSuccess();
  }
  
  return (
    <div className={`w-[40rem] max-w-[40rem] min-h-16 flex ${task.is_completed ? 'bg-green-400 bg-opacity-30' : 'bg-zinc-700'} rounded-md text-zinc-50 p-4 justify-between items-center text-lg`}>
      {
        enableEdit ?
          <input  
            className='bg-zinc-800 rounded-md h-10 w-full focus-visible:outline-none text-zinc-50 px-4'
            value={title} 
            onChange={handleTitleChange}
          ></input>
          : 
          <span className='ml-4 break-words break-all'>{task.title}</span>
      }
      {
        enableEdit ?
          <Button type='save' onClick={async () => await handleEditTask(task._id, {title})}/>
        :
          <div className='flex gap-2'>
            {
              task.is_completed ? 
                <Button type='restart' onClick={async () => await handleEditTask(task._id, { is_completed: false })}/>
              :
                <Button type='complete' onClick={async () => await handleEditTask(task._id, { is_completed: true })}/>
            }
            <Button type='edit' onClick={() => setEnableEdit(true)}/>
            <Button type='delete' onClick={async () => await handleDeleteTask(task._id)}/>
          </div>
      }
    </div>
  )
}

// frontend/angular/src/app/task/task.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { deleteTask } from '../../api/deleteTask';
import { editTask } from '../../api/editTask';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-task',
    templateUrl: './task.component.html',
    standalone: true,
    imports: [FormsModule, CommonModule],
})
export class TaskComponent {
    @Input() task: any;
    @Output() requestSuccess: EventEmitter<void> = new EventEmitter<void>();

    title: string = '';
    enableEdit: boolean = false;

    ngOnInit() {
        this.title = this.task.title;
    }

    handleTitleChange(event: Event): void {
        this.title = (event.target as HTMLInputElement).value;
    }

    async handleEditTask(id: string, title?: string, is_completed?: boolean): Promise<void> {
        const data = {
            title: title ?? this.task.title,
            is_completed: is_completed ?? this.task.is_completed,
        };
        await editTask(id, data);
        this.requestSuccess.emit();
        this.enableEdit = false;
    }

    async handleDeleteTask(id: string): Promise<void> {
        await deleteTask(id);
        this.requestSuccess.emit();
    }

    setEnableEdit(value: boolean): void {
        this.enableEdit = value;
    }
}

<div class="w-[40rem] max-w-[40rem] min-h-16 flex rounded-md text-zinc-50 p-4 justify-between items-center text-lg" [ngClass]="task.is_completed ? 'bg-green-400 bg-opacity-30' : 'bg-zinc-700'">
  <ng-container *ngIf="enableEdit; else displayTitle">
    <input  
      class="bg-zinc-800 rounded-md h-10 w-full focus-visible:outline-none text-zinc-50 px-4"
      [(ngModel)]="title"
      (input)="handleTitleChange($event)"
    />
  </ng-container>
  <ng-template #displayTitle>
    <span class="ml-4 break-words break-all">{{ task.title }}</span>
  </ng-template>
  <ng-container *ngIf="enableEdit; else displayButtons">
    <button 
      class="w-24 text-zinc-50 bg-blue-500 h-10 flex justify-center items-center rounded-r-md"
      (click)="handleEditTask(task._id, title)">
      Save
    </button>
  </ng-container>
  <ng-template #displayButtons>
    <div class="flex gap-2">
      <button 
        *ngIf="task.is_completed" 
        class="w-8 text-zinc-900 h-8 flex justify-center items-center rounded-r-md"
        (click)="handleEditTask(task._id, undefined, false)">
        <svg class="w-6 text-blue-300" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4.755 10.059a7.5 7.5 0 0 1 12.548-3.364l1.903 1.903h-3.183a.75.75 0 1 0 0 1.5h4.992a.75.75 0 0 0 .75-.75V4.356a.75.75 0 0 0-1.5 0v3.18l-1.9-1.9A9 9 0 0 0 3.306 9.67a.75.75 0 1 0 1.45.388m15.408 3.352a.75.75 0 0 0-.919.53a7.5 7.5 0 0 1-12.548 3.364l-1.902-1.903h3.183a.75.75 0 0 0 0-1.5H2.984a.75.75 0 0 0-.75.75v4.992a.75.75 0 0 0 1.5 0v-3.18l1.9 1.9a9 9 0 0 0 15.059-4.035a.75.75 0 0 0-.53-.918" clip-rule="evenodd"/></svg>
      </button>
      <button 
        *ngIf="!task.is_completed" 
        class="w-8 text-zinc-900 h-8 flex justify-center items-center rounded-r-md"
        (click)="handleEditTask(task._id, undefined, true)">
        <svg class="w-6 text-green-500" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75s-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12m13.36-1.814a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094z" clip-rule="evenodd"/></svg>
      </button> 
      <button 
        class="w-8 h-8 flex justify-center items-center"
        (click)="setEnableEdit(true)">
        <svg class="w-6 text-slate-50" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157l3.712 3.712l1.157-1.157a2.625 2.625 0 0 0 0-3.712m-2.218 5.93l-3.712-3.712l-12.15 12.15a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32z"/></svg>
      </button>
      <button 
        class="w-8 h-8 flex justify-center items-center"
        (click)="handleDeleteTask(task._id)">
        <svg class="w-6 text-red-500" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M16.5 4.478v.227a49 49 0 0 1 3.878.512a.75.75 0 1 1-.256 1.478l-.209-.035l-1.005 13.07a3 3 0 0 1-2.991 2.77H8.084a3 3 0 0 1-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 0 1-.256-1.478A49 49 0 0 1 7.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a53 53 0 0 1 3.369 0c1.603.051 2.815 1.387 2.815 2.951m-6.136-1.452a51 51 0 0 1 3.273 0C14.39 3.05 15 3.684 15 4.478v.113a50 50 0 0 0-6 0v-.113c0-.794.609-1.428 1.364-1.452m-.355 5.945a.75.75 0 1 0-1.5.058l.347 9a.75.75 0 1 0 1.499-.058zm5.48.058a.75.75 0 1 0-1.498-.058l-.347 9a.75.75 0 0 0 1.5.058z" clip-rule="evenodd"/></svg>
      </button>
    </div>
  </ng-template>
</div>
